version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright tests
          command: npx playwright test --grep=@smoke
      - persist_to_workspace:
          root: .
          paths:
            - playwright-report/
