version: 2.1

executors:
  pw-focal-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.35.0-jammy  # Specify the base Docker image for your tests
    environment:
      VARIABLE_NAME: value  # Define any required environment variables

jobs:
  job-name:
    executor: pw-focal-development
    parallelism: 4
    steps:
      - checkout
      - run: echo "Executor configuration for pw-focal-development"
      - run: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; npx playwright test -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}

workflows:
  version: 2
  my-workflow:
    jobs:
      - job-name