version: 2.1

parameters:
  commit:
    type: string
    default: "current"

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.35.0-jammy
    # Steps for the job
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run tests
          command: npx playwright test --grep=@smoke
          no_output_timeout: 10m
          environment:
            NO_COLOR: "1"

      - run:
          name: Process test results
          command: |
            if [ $? -eq 0 ]; then
              # All tests passed
              curl -X POST https://api.github.com/repos/AndriiFrolov/react-portfolio-app/statuses/<< pipeline.parameters.commit >> \
                -H "Authorization: Bearer $CIRCLE_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{
                  "state": "success",
                  "context": "circleci/tests",
                  "description": "All tests passed"
                }'
            else
              # At least one test failed
              curl -X POST https://api.github.com/repos/AndriiFrolov/react-portfolio-app/statuses/$CIRCLE_SHA1 \
                -H "Authorization: Bearer $CIRCLE_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{
                  "state": "failure",
                  "context": "circleci/tests",
                  "description": "Some tests failed"
                }'
              exit 1
            fi
          when: always

      - store_test_results:
          path: ./outcome/test-results/results.xml

      - store_artifacts:
          path: ./outcome/html

workflows:
  version: 2
  build:
    jobs:
      - run-test
