version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.35.0-jammy
    # Steps to the job
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run test
          command: npx playwright test --grep=@smoke
      - store_test_results:
          path: ./outcome/test-results/results.xml

      - store_artifacts:
          path: ./allure-results/

      - store_artifacts:
          path: ./outcome/html
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test